musicshop/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^search/', include('search.urls', namespace="search")),
    url(r'^hsearch/', include('haystack.urls')),
]

search/urls.py
from django.conf.urls import url

from .views import SongCreate, SongList, SuccessView, main, ajax_search, order

urlpatterns = [
    url(r'^$', main, name='main'),
    url(r'^ajax-search/$', ajax_search, name='ajax_search'),
    url(r'^create-song/$', SongCreate.as_view(), name='create_song'),
    url(r'^song-list/$', SongList.as_view(), name='song_list'),
    url(r'^thanks/$', SuccessView.as_view(), name='thanks'),
    url(r'^(?P<pk>[0-9]+)/$', order, name='order'),

]

search/models.py
from django.db import models


class Artist(models.Model):
    name = models.CharField(max_length=30, unique=True, db_index=True)

    def __str__(self):
        return self.name

    class Meta:
        """ Ordedering output by name. """
        ordering = ["name"]


class Song(models.Model):
    artist = models.ForeignKey(Artist, related_name='songs')
    title = models.CharField(max_length=50, unique=True, db_index=True)

    def __str__(self):
        return self.title

    class Meta:
        """ Ordedering output by title. """
        ordering = ["title"]


class Order(models.Model):
    song = models.ForeignKey(Song, related_name='orders')
    address = models.CharField(max_length=30)
    email = models.EmailField()
    name = models.CharField(max_length=30)
    surname = models.CharField(max_length=30)
    comment = models.TextField(blank=True)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '{0} - {1}'.format(self.song.artist, self.song)

search/forms.py
from django import forms

from .models import Order


class SearchForm(forms.Form):
    """ User search form. """

    required_css_class = 'control-label'

    query = forms.CharField(widget=forms.TextInput(
        attrs={'id': 'search-text', 'required': True, 'size': 50,
               'class': 'form-control'}),
        min_length=4, max_length=20)

    def clean_query(self):
        query = self.cleaned_data['query']
        query = query.split()
        for item in query:
            if len(item) < 3 or item == '-':
                query.remove(item)
        return query


class OrderForm(forms.ModelForm):
    """ Order creation form. """

    error_css_class = 'error'
    required_css_class = 'control-label'
    song = forms.IntegerField(widget=forms.HiddenInput())

    class Meta:
        model = Order
        fields = ['song', 'email', 'address', 'name', 'surname', 'comment']

    def __init__(self, *args, **kwargs):
        super(OrderForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'

search/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.core.mail import send_mail
from django.views.generic import CreateView, TemplateView, ListView
from musicshop.settings import EMAIL_HOST_USER

from .models import Artist, Song, Order
from .forms import SearchForm, OrderForm


class SongCreate(CreateView):
    model = Song
    template_name = 'search/create_song.html'
    fields = ['artist', 'title']

    def get_success_url(self):
        return reverse('search:thanks',)


class SongList(ListView):
    model = Song
    context_object_name = 'song_list'


class SuccessView(TemplateView):
    template_name = "search/thanks.html"


def main(request):
    """ Main page view. """
    if request.method == 'POST':
        form = SearchForm(request.POST)
        if form.is_valid():
            mess = form.cleaned_data['query']
            request.session["new"] = mess
    else:
        # GET /search/
        form = SearchForm()
    return render(request, 'search/main.html', {'form': form})


def ajax_search(request):
    """ Ajax search view that takes 1 or 2 words. """
    if request.method == 'POST':
        form = SearchForm(request.POST)
        if form.is_valid():
            mess = form.cleaned_data['query']
        else:
            mess = 'Bad request'

        mess_len = len(mess)
        artist = False
        song = False
        try:
            artist = Artist.objects.filter(name__icontains=mess[0])
        except Artist.DoesNotExist:
            pass

        if mess_len == 1:
            if artist:
                # search all song of artist, iterate in template
                pass
            else:
                # search in songs
                song = Song.objects.filter(title__icontains=mess[0])

        if mess_len == 2:
            # artist and song
            try:
                song = Song.objects.filter(title__icontains=mess[1])
            except Song.DoesNotExist:
                pass
            if artist and song:
                # search song of artist
                song = Song.objects.filter(
                    title__icontains=mess[1]).filter(
                        artist__name__icontains=mess[0])
            else:
                # search in songs(only song)
                song = Song.objects.filter(title__icontains=mess[1])
        return render(request, 'search/ajax_search.html', {
            'artist': artist,
            'song': song,
            'form_errors': form.errors
        })


def order(request, pk):
    """ View that accept and save music order to database. """
    song = Song.objects.get(id=pk)
    if request.method == 'POST':
        form = OrderForm(request.POST, instance=song)
        if form.is_valid():
            email = form.cleaned_data['email']
            address = form.cleaned_data['address']
            name = form.cleaned_data['name']
            surname = form.cleaned_data['surname']
            comment = form.cleaned_data['comment']
            message = 'Your order is {0} - {1}'.format(song.artist.name, song)
            sender = EMAIL_HOST_USER
            Order.objects.create(song=song, email=email, address=address,
                                 name=name, surname=surname, comment=comment)
            send_mail('Musicshop', message, sender, [email])
            return redirect(reverse('search:thanks'))
    else:
        form = OrderForm(initial={'song': song.id})
    return render(request, 'search/order_song.html',
                  {'song': song, 'form': form})

search/templates/search/_layout/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock title %}</title>
    {% block css %}{% endblock css %}
    {% block js %}{% endblock js %}
  </head>
  <body>
    {% block content %}{% endblock content %}
  </body>
</html>

search/templates/search/ajax-result.html
<table id="mus-t" class="table" cellspacing="0" width="500px">
    <thead>
        <tr>
            <th>Result:</th>
        </tr>
    </thead>
    <tbody>
        {% if artist and not song %}
            {% for art in artist %}
                {% for art2 in art.songs.all %}
                    <tr><td><a href="{{ art2.id }}">{{ art }} - {{ art2 }}</a></td></tr>
                {% endfor %}
            {% endfor %}
        {% else %}
            {% for mys in song  %}
                <tr><td><a href="{{ mys.id }}">{{ mys.artist }} - {{ mys }}</a></td></tr>
            {% endfor %}
        {% endif %}
        
        <tr><td>{{ form.errors }}</td></tr>
    </tbody>
</table>

search/templates/search/ajax_result.html
<table id="mus-t" class="table" cellspacing="0" width="500px">
    <thead>
        <tr>
            <th>Result:</th>
        </tr>
    </thead>
    <tbody>
        {% if artist and not song %}
            {% for art in artist %}
                {% for art2 in art.songs.all %}
                    <tr><td><a href="{{ art2.id }}">{{ art }} - {{ art2 }}</a></td></tr>
                {% endfor %}
            {% endfor %}
        {% else %}
            {% for mys in song  %}
                <tr><td><a href="{{ mys.id }}">{{ mys.artist }} - {{ mys }}</a></td></tr>
            {% endfor %}
        {% endif %}
        
        {% if not artist and not song %}
            <tr><td>Nothing found</td></tr>
        {% endif %}

        <tr><td>{{ form.errors }}</td></tr>
    </tbody>
</table>

search/templates/search/ajax_search.html
<table id="mus-t" class="table" cellspacing="0" width="500px">
    <thead>
        <tr>
            <th>Result:</th>
        </tr>
    </thead>
    <tbody>
        {% if artist and not song %}
            {% for art in artist %}
                {% for art2 in art.songs.all %}
                    <tr><td><a href="{{ art2.id }}">{{ art }} - {{ art2 }}</a></td></tr>
                {% endfor %}
            {% endfor %}
        {% else %}
            {% for mys in song  %}
                <tr><td><a href="{{ mys.id }}">{{ mys.artist }} - {{ mys }}</a></td></tr>
            {% endfor %}
        {% endif %}
        
        {% if not artist and not song %}
            <tr><td>Nothing found</td></tr>
        {% endif %}

        <tr><td>{{ form.errors }}</td></tr>
    </tbody>
</table>

search/templates/search/create_song.html
{% extends 'search/_layout/base.html' %}
{% load staticfiles %}

{% block title %}Order page{% endblock title %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'search/css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
{% endblock css %}
{% block js %}{% endblock js %}

{% block content %}
<div class="order-block">
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Create" />
    </form>
</div>
{% endblock content %}

search/templates/search/main.html
{% extends 'search/_layout/base.html' %}
{% load staticfiles %}

{% block title %}Main page{% endblock title %}
{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'search/css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
{% endblock css %}
{% block js %}
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="http://malsup.github.com/jquery.form.js"></script> 
    <script src="{% static 'search/js/main.js' %}"></script>
{% endblock js %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <div class="order-title">
                <a href="{% url 'search:song_list' %}">Song list</a>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <div class="search-block">
                <form id="post-form" method="post" action="{% url 'search:ajax_search' %}">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <div class="form-group">
                        <div>
                            <input type="submit" class="btn btn-default" value="Search" />
                        </div>
                    </div>
                </form>
            </div>
            <!-- Response -->
            <div id="resp" class="resp-block"></div>
        </div>
    </div>
</div>
{% endblock content %}

search/templates/search/new_song.html
{% extends 'search/_layout/base.html' %}
{% load staticfiles %}

{% block title %}Order page{% endblock title %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'search/css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
{% endblock css %}
{% block js %}{% endblock js %}

{% block content %}
<div class="order-block">
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Create" />
    </form>
</div>
{% endblock content %}

search/templates/search/order_song.html
{% extends 'search/_layout/base.html' %}
{% load staticfiles %}

{% block title %}Order page{% endblock title %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'search/css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
{% endblock css %}
{% block js %}{% endblock js %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <div class="order-block">
                <h4 class="order-center">Order Song:</h4>
                <p class="order-title">{{ song.artist }} - {{ song }}</p>
                <form id="order-form" method="post" action="">
                    {% csrf_token %}
                    {# Include the hidden fields in the form #}
                    {% if form.non_field_errors %}
                        <div class="form_errors">
                        {% for err in form.non_field_errors %}
                            <div class="form_error_message">{{ err }}</div>
                        {% endfor %}
                        </div>  
                    {% endif %}

                    {% for hidden in form.hidden_fields %}
                       {{ hidden }}
                    {% endfor %}

                    {% for field in form.visible_fields %}
                        <div class="form-group">
                            {{ field.label_tag }}
                            {{ field }}
                        {% for err in field.errors %}
                            <span class="error_message">{{ err }}</span>
                        {% endfor %}
                        </div>
                    {% endfor %}

                    <div class="form-group">
                        <div>
                            <input type="submit" class="btn btn-default" value="Send" />
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

search/templates/search/search.html
{% extends 'search/_layout/base.html' %}
{% load staticfiles %}

{% block title %}Order page{% endblock title %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'search/css/style.css' %}">
{% endblock css %}
{% block js %}{% endblock js %}


{% block content %}
    <h2>Search</h2>

    <form method="get" action=".">
        <table>
            {{ form.as_p }}
            <tr>
                <td>&nbsp;</td>
                <td>
                    <input type="submit" value="Search">
                </td>
            </tr>
        </table>

        {% if query %}
            <h3>Results</h3>

            {% for result in page.object_list %}
                <p>
                    {{ result.object.artist }} - {{ result.object.title }}
                </p>
            {% empty %}
                <p>No results found.</p>
            {% endfor %}

        {% else %}
            {# Show some example queries to run, maybe query syntax, something else? #}
        {% endif %}
    </form>
{% endblock %}

search/templates/search/song_list.html
{% extends 'search/_layout/base.html' %}
{% load staticfiles %}

{% block title %}Order page{% endblock title %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'search/css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
{% endblock css %}
{% block js %}{% endblock js %}

{% block content %}
<div class="song-list-block">
<table id="mus-t" class="table" cellspacing="0" width="500px">
    <thead>
        <tr>
            <th>Song list:</th>
        </tr>
    </thead>
    <tbody>
        {% for song in song_list %}
            <tr><td><a href="{{ song.id }}">{{ song.artist }} - {{ song.title }}</a></td></tr>
        {% empty %}
            <tr><td>No songs</td></tr>
        {% endfor %}

    </tbody>
</table>
    <p><a href="{% url 'search:create_song' %}" class="btn btn-default">Create a new song</a></p>
</div>
{% endblock content %}

search/templates/search/thanks.html
{% extends 'search/_layout/base.html' %}
{% load staticfiles %}

{% block title %}Order page{% endblock title %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'search/css/style.css' %}">
{% endblock css %}
{% block js %}{% endblock js %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <div class="thanks-block">
                <h3>Thanks!</h3>
                <p>Your order has been accepted.</p>
            </div>
        </div>
    </div>
</div>
{% endblock content %}